# -*- coding: utf-8 -*-
"""
Created on Sun Feb 28 20:48:22 2021

@author: Matth
"""
## LAMBDA FUNCTIONS
## MODULES CLASSES AND OBJECTS
## LEARNING TO SPEAK OBJECT ORIENTED
## CLASSES/ OBJECTS /
## INHERITENCE VS COMPOSITION
## MODULES
